# Dockerfile.Backend

FROM node:18-alpine

WORKDIR /app

# COPY FROM actual relative path to inside the container
COPY Backend/package*.json ./
RUN npm install

COPY Backend/ .

EXPOSE 3000

CMD ["node", "index.js"]
