# # Dockerfile.Backend

# FROM node:18-alpine

# WORKDIR /app

# COPY Backend/package*.json ./
# RUN npm install

# COPY Backend/ .

# EXPOSE 3000

# CMD ["node", "index.js"]
# Backend Dockerfile
FROM node:18.20.8
WORKDIR /app
COPY package*.json ./  
RUN npm install        
COPY . .              
CMD ["node", "index.js"]
