version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/index
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
