version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
    depends_on:
      - mongo
    working_dir: /app
    command: ["node", "index.js"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
    working_dir: /app
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:4.4   
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
