version: '3.8'

services:
  mongo:
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend

volumes:
  mongo-data:
